### ISSUE TITLE
Cell sizes

### ISSUE THREAD

**Issue by Levsha1337** [AreebKhan619/2048#1]
When i getting 1024 and more your cells breaks on borders:
![image](https://user-images.githubusercontent.com/27131453/115472486-9f5ac780-a242-11eb-8d1e-fedc8cf091d4.png)

**Comment by AreebKhan619** [comment]
Hi, thanks for adding this issue. Can I know the screen size / resolution of the device you're using it on? Also knowing the browser name and version would be helpful in duplicating this issue.

**Comment by Levsha1337** [comment]
> Hi, thanks for adding this issue. Can I know the screen size / resolution of the device you're using it on? Also knowing the browser name and version would be helpful in duplicating this issue.

Windows 10, Yandex.Browser (yandex is russian company like google, that browser based on chromium, i think problem will represent on Chrome too)
1920x1080.

**Comment by Levsha1337** [comment]
Yeap, google chrome:
![image](https://user-images.githubusercontent.com/27131453/116000035-42229580-a5f7-11eb-9164-700f44cf5907.png)

**Comment by AreebKhan619** [comment]
Thanks for providing the info, was asking because my own laptop resolution was 1366 x 768 and couldn't see it. I've fixed this, kindly confirm from your end so that I can close this issue. (commit reference ID: 876edad367c9e2792dc0aa9481d7e8ed0471ba2c)

**Comment by Levsha1337** [comment]
![image](https://user-images.githubusercontent.com/27131453/116239529-6e5f2300-a76b-11eb-9f1b-c10327cc5a50.png)
Yep, its okay now. Good job!
